### ISSUE TITLE
failed to set 'from' and 'to' formats: inchi inchikey

### ISSUE THREAD

**Issue by JustinZZW** [nanxstats/Rcpi#10]
Hi Nan,
I come across a problem when using convertMolFormat Function. This function work well when using example data. But the errors occured when I hope to convet from inchi to inchikey. The file was attached. [test.zip](https://github.com/nanxstats/Rcpi/files/4675996/test.zip)

The code I used:
```
convMolFormat(infile = './test.inchi', outfile = 'test.inchikey', from = 'inchi', to = 'inchikey') 
```

The error:
```
Error in ChemmineOB::convertFormatFile(from = from, to = to, fromFile = infile,  : 
  failed to set 'from' and 'to' formats: inchi inchikey
```

I would appeciate a lot for your kindness helps

Best,

Zhiwei

**Comment by nanxstats** [comment]
Hmm, the issue seem to be rooted in the ChemmineOB wrapper, not much I can do from my side. I'd say it would be sufficient to call openbabel from the command line as an ad-hoc solution:

```r
system("obabel -iinchi test.inchi -oinchikey > test.inchikey")
```

**Comment by JustinZZW** [comment]
Great! It works perfectly. Thanks a lot.
