### ISSUE TITLE
error with tutorial

### ISSUE THREAD

**Issue by salwan96** [nanxstats/Rcpi#4]
Hi, I am learning the Rcpi package, I was successfully able to install and run the package, and I attempting to replicate section 3.4 (Structure-Based Chemical Similarity Searching), I have loaded mol, and moldb files, DB00530.sdf and tyrphostin.sdf respectively, but when I run drug similarity search using code from the tutorial:

rank1 = searchDrug(
  mol, moldb, cores = 4, method = "fp",
  fptype = "maccs", fpsim = "tanimoto")

I encounter the error:

Error in order(..., decreasing = decreasing) : 
  unimplemented type 'list' in 'orderVector1'

I did some searching but I don't understand why this error occurs, any help would be appreciated, thanks

**Comment by nanxstats** [comment]
@salwan96 -hmm, that's weird. The following example code runs ok on my machine (assuming you're using the same code). I'm running on R 3.5.1/BioC 3.8:

```r
library("Rcpi")

mol <- system.file("compseq/DB00530.sdf", package = "Rcpi")
moldb <- system.file("compseq/tyrphostin.sdf", package = "Rcpi")

rank1 <- searchDrug(
  mol, moldb,
  cores = 4, method = "fp",
  fptype = "maccs", fpsim = "tanimoto"
)

head(rank1)
# 92       100        83       101         1        36
# 0.6491228 0.6491228 0.5882353 0.5660377 0.5000000 0.5000000
```

Maybe upgrading R and the packages to the latest stable version? Or, please send in the code and data so I can reproduce the issue.

Thanks!

**Comment by salwan96** [comment]
Thanks for the reply, I updated all packages and it is working now, thanks

**Comment by nanxstats** [comment]
@salwan96 -great! Glad it works. 😄
