### ISSUE TITLE
Returns empty string when using getSmiFromPubChem

### ISSUE THREAD

**Issue by futsuunohito** [nanxstats/Rcpi#8]
Hi,

the function getSmiFromPubChem returns an empty string ("") when the id is a singular string, but when the id is a list of string, it works.

**Comment by nanxstats** [comment]
Hmm, that's probably related to how it was implemented. Usually one would expect to get SMILES for a batch of IDs in a single call, instead of feeding a single ID and looping over.

It's true that this edge case needs a fix though.

**Comment by futsuunohito** [comment]
in my case, I used the function on a data frame iteration, in which I used it per iteration. I did this because the dataset consists of multiple sources (drugbank, kegg, etc.). Would you mind giving it a fix? Thanks in advance

**Comment by futsuunohito** [comment]
@nanxstats I find another bug in getSmiFromDrugBank. Some of the drugbank ids doesn't have an SDF file that is available to be accessed. For example, the id "DB00729" when accessed through "https://www.drugbank.ca/drugs/DB00729", it redirected to "https://www.drugbank.ca/salts/DBSALT002847" instead. Which means although the ID has correctly redirected the user the actual page, your code failed to access its SDF at "https://www.drugbank.ca/structures/small_molecule_drugs/DB00729.sdf" because it does not exist.

Please correct me if I wrong, thanks

**Comment by nanxstats** [comment]
-ok, I will look into them.

**Comment by nanxstats** [comment]
Hi @futsuunohito -the first single ID edge case has been fixed. You can install the GitHub version and here's an example:

```r
library("Rcpi")
id = "7847562"
getSmiFromPubChem(id)
```

I also looked into the the second "bug" but it seems any "fix" will make the logic more complicated than it should be --- as the ID of salts (product ingredients) should be converted to the actual drug (active moiety) ID locally first. For the above example, DB00729 is not an active drug ID anymore, and DBSALT002847 should point to DB13720. It is much easier to do this on the user's end. Other packages dedicated to DrugBank data access such as [drugbankR](https://github.com/yduan004/drugbankR) or [dbparser](https://cran.r-project.org/package=dbparser) might be useful for such purposes.
